<a href="https://colab.research.google.com/github/irfan-ardiansyah/data-science-2026/blob/main/Pertemuan_2_Muhammad_Irfan_Ardiansyah_250401020175_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Science - Pertemuan 2

Nama  : **Muhammad Irfan Ardiansyah** <br>
NIM   : **250401020175** <br >
Kelas : **IF401**

In [13]:
import pandas as pd
import numpy as np

URL = "http://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

df = pd.read_csv(URL)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [14]:
print(df.shape, df.columns.tolist())
print("-----------------------------")
print(df.isnull().sum())

(891, 12) ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
-----------------------------
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [15]:
# Filtering — Penumpang Wanita Kelas 1
wk1 = df[(df['Sex']=='female') & (df['Pclass']==1)]
wk1

# Rounding result

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [16]:
mean_survived = wk1['Survived'].mean()
mean_age = wk1['Age'].mean()

print("============== Raw Result ===============")
print("mean of survived:", mean_survived)
print("mean of age:", mean_age)

print("\n============== Rounded Result ===============")
print("mean of survived:", round(mean_survived, 3))
print("mean of age:", round(mean_age, 3))

============== Raw Result ===============
mean of survived: 0.9680851063829787
mean of age: 34.61176470588235

============== Rounded Result ===============
mean of survived: 0.968
mean of age: 34.612

In [17]:
# Groupby — Tingkat Keselamatan per Kelas
hasil = df.groupby('Pclass').agg(total=('PassengerId','count'), selamat=('Survived','mean')).round(3)
print(hasil)

        total  selamat
Pclass
1         216    0.630
2         184    0.473
3         491    0.242

In [18]:
# Jawaban
print("1. Jumlah baris & kolom")
print("baris:", df.shape[0])
print("kolom", df.shape[1])
print("\n")

print("2. Kolom yang bernilai kosong")
print("Kolom kosong:", df.columns[df.isnull().sum() != 0].tolist())
print("\n")

print("3. Persentase penumpang selamat")
survived = len(df[(df["Survived"]==1)]) / df.shape[0] * 100
print(round(survived, 2), "%")
print("\n")


print("4. Rata-rata usia penumpang wanita kelas 1 yang selamat")
print(round(mean_age, 2), "%")
print("\n")


print("5. Kelas penumpang mana yang tingkat keselamatan tertinggi")
print("Kelas ", hasil["selamat"].idxmax() )
print("\n")


print("6. Tampilkan hasil groupby('Pclass')['Survived'].mean()")
print(df.groupby("Pclass")['Survived'].mean().round(2) )
print("\n")

1. Jumlah baris & kolom
baris: 891
kolom 12


2. Kolom yang bernilai kosong
Kolom kosong: ['Age', 'Cabin', 'Embarked']


3. Persentase penumpang selamat
38.38 %


4. Rata-rata usia penumpang wanita kelas 1 yang selamat
34.61 %


5. Kelas penumpang mana yang tingkat keselamatan tertinggi
Kelas  1


6. Tampilkan hasil groupby('Pclass')['Survived'].mean()
Pclass
1    0.63
2    0.47
3    0.24
Name: Survived, dtype: float64

## Kesimpulan
Pada pertemuan ini membahas tentang load data csv untuk diolah, aplikasi filter sederhana. Saya mempelajari bagaimana untu missing value dan penyajian data sederhana

## Pertanyaan
Bagaimana jika data berasal dari database seperti MySQL, PostgreSQL, apakah prosesnya akan sama?